// Syntax documentation: https://dbml.dbdiagram.io/docs/

//////////////////////////////////////////////////////
// STORE STRUCTURE SECTION
//////////////////////////////////////////////////////

Table floor {
  note: "A store can have one or multiple floors."
  
  id int [not null, pk, increment]

  number int [not null, default: 1, note: "One stands for the ground floor, two for the 2nd floor, etc."]
  store_id int [not null, ref: > store.id]

  indexes {
    store_id
  }
}

Table store {
  note: "Physical store with size and geolocation."

  id int [not null, pk, increment]

  name varchar(63) [not null]
  logo_url varchar(255) [not null]
  image_url varchar(255) [note: "If not provided, the logo displayed instead."]
  description varchar(255)
  
  longitude double
  latitude double

  indexes {
    name
  }
}

//////////////////////////////////////////////////////
// LOCATION REPRESENTATION SECTION
//////////////////////////////////////////////////////

Enum node_type {
  navigation [note: "Either store corners or aisle intersections."]

  // Should be defined for all floor except the highest one.
  elevation [note: "An elevator or staircase to the level above."]
  // Should be defined for all floors except the ground one.
  descent [note: "An elevator or staircase to the level below."]
}

Table node {
  note: "User reachable area."
  
  id int [not null, pk, increment]
  floor_id int [not null, ref: > floor.id]

  number int [not null]
  type node_type [not null, default: node_type.navigation]
  name varchar(63) [note: "e.g. \"Start of the principal corridor\", \"Milk-toys intersection\""]

  indexes {
    floor_id
  }
}

Table edge {
  note: "Represents an aisle between two reachable points."

  id int [not null, pk, increment]
  floor_id int [not null, ref: > floor.id]

  // These two must be on the same floor id.
  // That id must be the same as this edge floor id.
  source_node_id int [not null, ref: > node.id]
  target_node_id int [not null, ref: > node.id]

  name varchar(63) [note: "e.g. \"milk corridor\""]
  weight int

  checks {
    `source_node_id != target_node_id` [name: "An edge must be between two different nodes."]
  }

  indexes {
    floor_id
  }
}

//////////////////////////////////////////////////////
// PRODUCT SECTION
//////////////////////////////////////////////////////

Table stand {
  note: "Links a specific place on a shelf to an article."
  
  edge_id int [not null, ref: > edge.id]
  article_id int [not null, ref: > article.id]

  source_node_distance int [not null]

  indexes {
    (edge_id, article_id) [pk]
  }
}

// There is a hidden one-one relationship between an article and a store.
Table article {
  note: "Product instance placed at a specific location."

  id int [not null, pk, increment]
  product_id int [not null, ref: > product.id]
  
  amount double [not null, note: "This is decided by each store individually."]
  currency varchar(255)
}

Table product {
  note: "Product details."

  id int [not null, pk, increment]
  
  variant varchar(63) [note: "e.g. almond milk"]
  subcategory varchar(63) [not null, note: "e.g. milk"]
  category varchar(63) [not null, note: "e.g. dairy products"]

  vendor varchar(63) [note: "e.g. Zuzu, Alpro, etc."]
  image_url varchar(255)
  description varchar(255)

  indexes {
    vendor
  }
}

//////////////////////////////////////////////////////
// DISCOUNT SECTION
//////////////////////////////////////////////////////

Table discount {
  note: "Links an offer to discounted articles."

  article_id int [not null, ref: > article.id]
  offer_id int [not null, ref: > offer.id]

  indexes {
    (offer_id, article_id) [pk]
  }
}

Table offer {
  note: "Promotional offer with optional period or dependency."

  id int [not null, pk, increment]
  period_id int [ref: > period.id, note: "Optional active time period in a day."]
  dependency_id int [ref: > dependency.article_id, note: "e.g. \"Buy one orange to get an discount to the second one\"."]

  percentage int [not null]
  created_at datetime [not null]
  lifetime datetime
}

Table period {
  note: "Daily time window for an offer."

  id int [not null, pk, increment]
  
  begin datetime [not null, default: "00:00", note: "Start time of offer."]
  end datetime [not null, default: "23:59", note: "End time of offer."]
}

Table dependency {
  note: "Required product quantity to activate an offer."

  article_id int [not null, pk, ref: > article.id]
  quantity int
}
